### Importing Libraries

In [14]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from colorama import Fore
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [15]:
os.listdir( '../data/preprocessed data' )

['pre-processed_data.csv']

In [16]:
df = pd.read_csv( '../data/preprocessed data/pre-processed_data.csv' )

In [17]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
13885,male,Bachelor of Science,2.35,44.2,yes,8.7,0,coaching,0,1,59.3,5

## Split features into X & y

In [18]:
X = df.drop( columns = 'exam_score' )
y = df['exam_score']

In [19]:
X.shape

(20000, 11)

## Split into training & testing

In [20]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [21]:
X_train

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,course_diff
5894,other,Bachelor of Commerce,6.87,57.1,no,9.0,2,group study,0,2,2
3728,other,Bachelor of Arts,6.91,54.8,yes,9.1,2,mixed,1,2,1
8958,other,Bachelor of Arts,5.45,99.4,yes,7.6,1,group study,1,1,1
7671,other,Bachelor of Arts,4.73,47.6,yes,7.0,0,group study,2,1,1
5999,female,Bachelor of Computer Applications,3.81,78.6,yes,7.8,2,group study,2,1,4
...,...,...,...,...,...,...,...,...,...,...,...
11284,female,Bachelor of Commerce,7.36,98.8,yes,7.1,0,mixed,1,2,2
11964,male,Bachelor of Business Administration,5.83,99.0,yes,9.6,0,self-study,2,0,3
5390,male,Bachelor of Arts,1.49,80.1,yes,7.1,2,mixed,1,1,1
860,male,Bachelor of Computer Applications,0.28,52.1,yes,7.1,2,online videos,2,1,4
15795,male,Bachelor of Science,0.59,67.6,no,9.1,2,coaching,0,0,5

# Model Selection

### Ensemble models

In [22]:
knn_model = KNeighborsRegressor( n_neighbors= 1 )

In [23]:
X_train.shape

(16000, 11)

In [24]:
X_test.shape

(4000, 11)

In [25]:
y_test

10650     31.1
2041      81.6
8668      68.0
1114     100.0
13902     84.8
         ...
4073      58.6
7442      53.3
9999      58.8
1870      45.3
15196     42.7
Name: exam_score, Length: 4000, dtype: float64

## Pre-Processing

In [26]:
knn_model.fit( X_train, y_train )

ValueError: could not convert string to float: 'other'

In [ ]:
y_pred_train = knn_model.predict( X_train )
y_pred_train[:5]

In [ ]:
y_test[100:106]

In [ ]:
18 / 3

In [ ]:
y_pred_test = knn_model.predict( X_test )

In [ ]:
y_pred_test[100:106]

In [ ]:
pd.DataFrame({
    'Actual' : y_test[100:106],
    'Predicted' : y_pred_test[100:106],
    'Residuals' : y_test[100:106] - y_pred_test[100:106]
})

In [ ]:
0.5 + 15.3 + 6.3 + 4.9

## metrics

### MAE ( Mean Absolute Error ) ->  Look on the Avg. Error
### MSE ( Mean Squared Error )  ->  Triggers if there is high residuals (differences)
### RMSE ( Root Mean Squared Error ) -> Error between MAE & MSE

In [ ]:
MAE_train = mean_absolute_error( y_train, y_pred_train )
MAE_test = mean_absolute_error( y_test, y_pred_test )


MSE_train = mean_squared_error( y_train, y_pred_train )
MSE_test = mean_squared_error( y_test, y_pred_test )

RMSE_train = root_mean_squared_error( y_train, y_pred_train )
RMSE_test = root_mean_squared_error( y_test, y_pred_test )



print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )

print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

### Evaluation of previous n_neighbors = 5
**9.4, 136, 11.6**

### Calc. Cross Validation Score

In [ ]:
cross_val_score( knn_model, X_train, y_train, cv= 4, scoring='neg_mean_squared_error' ).mean()

In [ ]:
pd.set_option( 'display.max_columns', None )

In [ ]:
X_train.sample()

In [ ]:
234.81223721774998 ** 0.5

## Curse of Dimensiality

## Fine Tuning

# Testing

In [ ]:
df.sample()

## Testing GridSearchCV on KNN Model

In [ ]:
knn_model = KNeighborsRegressor(  )

In [ ]:
gs_knn =  GridSearchCV(
    estimator= knn_model,
    param_grid= { 'n_neighbors' : [ 2, 3, 4, 5, 6, 7 ] }
)

In [ ]:
gs_knn.fit( X_train, y_train )

In [ ]:
gs_knn.best_params_

In [ ]:
y_test

In [ ]:
y_pred_test

In [ ]:
knn_comparison_df = pd.DataFrame({
    'Actual (True)' : y_test,
    'Predicted (KNN)' : y_pred_test,
    'Residuals' : np.abs( y_test- y_pred_test )
})
knn_comparison_df

In [ ]:
knn_comparison_df

## Visulauize Residuals

In [ ]:
px.line( knn_comparison_df.head( 25 ), x  = ['Actual (True)', 'Predicted (KNN)'] )

In [ ]:
knn_comparison_df.head( 25 )

In [ ]:
px.histogram( knn_comparison_df, x  = ['Actual (True)', 'Predicted (KNN)'] )

<hr>

# [2] Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg_model = LinearRegression()

In [ ]:
os.cpu_count()

In [ ]:
lin_reg_model.fit( X_train, y_train )

In [ ]:
y_pred_train_lr = lin_reg_model.predict( X_train )
y_pred_test_lr = lin_reg_model.predict( X_test )

In [ ]:
y_pred_train_lr

In [ ]:
y_train

# Intercept -> b

In [ ]:
lin_reg_model.intercept_

In [ ]:
X_train.shape

In [ ]:
lin_reg_model.coef_

### Optimization Algorithm

In [ ]:
X_train.columns

## Y = b + p1x1 + p2x2 + p3x3 + p4x4 +  .......... p24x24

In [ ]:
print( 'Linear Regression Evaluation :' )
print( '-------------------------' )
print(  )

MAE_train = mean_absolute_error( y_train, y_pred_train_lr )
MAE_test = mean_absolute_error( y_test, y_pred_test_lr )


MSE_train = mean_squared_error( y_train, y_pred_train_lr )
MSE_test = mean_squared_error( y_test, y_pred_test_lr )

RMSE_train = root_mean_squared_error( y_train, y_pred_train_lr )
RMSE_test = root_mean_squared_error( y_test, y_pred_test_lr )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )

print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

### Model Serialization ( Saving ) ( Dumping )
#### Save to extension .pkl

In [ ]:
import joblib
import pickle

In [ ]:
lin_reg_model

In [ ]:
os.listdir( '../artifacts' )

In [ ]:
# joblib.dump( lin_reg_model, '../artifacts/exam_score_model.pkl' )

In [ ]:
df.sample()

In [ ]:
df.shape

### Define a function to evaluate any regressor

In [ ]:
#### model

In [ ]:
from colorama import Fore

In [ ]:
print(  Fore.MAGENTA + 'hello' )

In [28]:
def evaluate_regressor( model, model_name: str ,X_train, X_test, y_train, y_test  ) :
    
    print( 'Training.........' + '\n' )
    
    print( model_name + ':' )
    print( '-'*20 )
    
    model.fit( X_train, y_train ) # Training !
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict( X_test )

    print(  )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print(  )

    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )

## [1] KNN

In [ ]:
knn_model = KNeighborsRegressor( n_neighbors=7 )

In [ ]:
evaluate_regressor( knn_model, 'K Neighbors Regressor', X_train, X_test, y_train, y_test )

## [2] Linear Regression

In [ ]:
lin_reg_model = LinearRegression()

In [ ]:
evaluate_regressor( lin_reg_model, 'Linear Regression without regularization', X_train, X_test, y_train, y_test  )

## [3] Linear Regression with regularization L1 ( Lasso )

In [ ]:
lin_reg_L1 = Lasso( alpha = 0.2 )

In [ ]:
evaluate_regressor( lin_reg_L1, 'Linear Regression with REGULARIZATION ( L1 )', X_train, X_test, y_train, y_test  )

## [4] Linear Regression with regularization L2 ( Ridge )

In [ ]:
ridge = Ridge(  )

In [ ]:
evaluate_regressor( ridge, 'Linear Regression with REGULARIZATION ( L2 )', X_train, X_test, y_train, y_test  )

## [5] Support Vector Machine

In [ ]:
from sklearn.svm import SVR

In [ ]:
svm_regressor = SVR(  )

In [ ]:
evaluate_regressor( svm_regressor, 'SVM', X_train, X_test, y_train, y_test  )

## [6] Support Vector Machine with Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [ ]:
svm_pipeline =   make_pipeline(
    StandardScaler(),
    svm_regressor
)

### Model Serialization ( Saving ) ( dumping )

In [ ]:
svm_pipeline

In [34]:
import joblib
joblib.dump( svm_pipeline, '../artifacts/svm_pipeline.pkl' )

['../artifacts/svm_pipeline.pkl']

In [ ]:
evaluate_regressor( svm_pipeline, 'SVM With Scaling', X_train, X_test, y_train, y_test  )

### Try Fine-Tuning

### if kernel == 'poly' --> higher degree -> pruning overfitting

#### if gamma small -> try not to fit all data -> high error -> underfitting
#### if gamma high -> FIT ALL THE DATA AS POSSIBLE -> low error -> overfitting

<hr>

## C
#### C -> regularization parameter
#### High C -> model tries hard to fit all data -> risk overfitting
#### Low C -> model allows erros -> risk underfitting

<hr>

In [14]:
df.columns

Index(['gender', 'course', 'study_hours', 'class_attendance',
       'internet_access', 'sleep_hours', 'sleep_quality', 'study_method',
       'facility_rating', 'exam_difficulty', 'exam_score', 'course_diff'],
      dtype='object')

### Test the One-Hot Encoder class

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import SVR
from sklearn.compose import ColumnTransformer

### Creating one-hot encoding step

In [38]:
X_train.columns

Index(['gender', 'course', 'study_hours', 'class_attendance',
       'internet_access', 'sleep_hours', 'sleep_quality', 'study_method',
       'facility_rating', 'exam_difficulty', 'course_diff'],
      dtype='object')

In [41]:
one_hot_encoding_step  = ColumnTransformer(transformers=[
    ( 'One-Hot Encoding', OneHotEncoder(), [ 'gender', 'course', 'internet_access', 'study_method' ] )
], remainder= 'passthrough')
one_hot_encoding_step

ColumnTransformer(remainder='passthrough',
                  transformers=[('One-Hot Encoding', OneHotEncoder(),
                                 ['gender', 'course', 'internet_access',
                                  'study_method'])])

In [43]:
svm_pipeline = Pipeline( steps = [
    ( 'One-Hot Encoding',one_hot_encoding_step ),
    ( 'Scaling', StandardScaler() ),
    ( 'Model', SVR() )
] )

In [44]:
svm_pipeline

Pipeline(steps=[('One-Hot Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('Scaling', StandardScaler()), ('Model', SVR())])

In [45]:
evaluate_regressor( svm_pipeline, 'SVM with One-Hot Encoding & Scaling', X_train, X_test, y_train, y_test )

Training.........

SVM with One-Hot Encoding & Scaling:
--------------------

Mean Absolute Error of training : 7.764041233121284
Mean Squared Error of training : 95.38082144872725
Root Mean Squared Error of Training : 9.766310534113035

Mean Absolute Error of Testing : 8.026937148942237
Mean Squared Error of Testing : 98.94547004435063
Root Mean Squared Error of Testing : 9.947133760252278

In [46]:
import joblib

In [47]:
svm_pipeline

Pipeline(steps=[('One-Hot Encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('Scaling', StandardScaler()), ('Model', SVR())])

In [48]:
joblib.dump( svm_pipeline, '../artifacts/svm_pipeline.pkl' )

['../artifacts/svm_pipeline.pkl']